/* Groups */
CREATE ROLE Human
	CONNECTION LIMIT -1;

CREATE ROLE Admin
	WITH SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS
	CONNECTION LIMIT 1
	IN ROLE Human;

CREATE ROLE Client
	WITH BYPASSRLS
	CONNECTION LIMIT -1
	IN ROLE Human;

CREATE ROLE Service
	CONNECTION LIMIT -1;

/* Users */
CREATE USER xibitol
	WITH SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS
	PASSWORD NULL
	IN ROLE Admin;

/* DATABASES PRIVILEGES */
REVOKE ALL PRIVILEGES ON DATABASE postgres FROM PUBLIC CASCADE;
REVOKE ALL PRIVILEGES ON DATABASE template0 FROM PUBLIC CASCADE;
REVOKE ALL PRIVILEGES ON DATABASE template1 FROM PUBLIC CASCADE;

GRANT ALL PRIVILEGES ON DATABASE postgres TO Admin;
GRANT ALL PRIVILEGES ON DATABASE template0 TO Admin;
GRANT ALL PRIVILEGES ON DATABASE template1 TO Admin;