Subsystem sftp internal-sftp

UseDNS no

Match Group sftp-allowed
	ForceCommand internal-sftp -d /%u

	ChrootDirectory /home/sftphomes

	PasswordAuthentication yes
	PermitRootLogin no
	X11Forwarding no
	AllowTcpForwarding no
	AllowAgentForwarding no
	PermitTunnel no