/* Groups */
CREATE ROLE Human
	CONNECTION LIMIT -1;

CREATE ROLE Admin
	WITH SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS
	CONNECTION LIMIT 1
	IN ROLE Human;

CREATE ROLE Client
	WITH BYPASSRLS
	CONNECTION LIMIT -1
	IN ROLE Human;

CREATE ROLE Service
	CONNECTION LIMIT -1;

/* Users */
CREATE USER xibitol
	WITH SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS
	PASSWORD NULL
	IN ROLE Admin;
