CREATE ROLE Human
	WITH NOINHERIT
	CONNECTION LIMIT -1;

CREATE ROLE Admin
	WITH SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS
	CONNECTION LIMIT 1
	IN ROLE Human;

CREATE ROLE Client
	WITH BYPASSRLS
	CONNECTION LIMIT -1
	IN ROLE Human;

CREATE ROLE Service
	WITH NOINHERIT
	CONNECTION LIMIT -1;